services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: semafori-mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    restart: unless-stopped

  influxdb:
    image: influxdb:2.7
    container_name: semafori-tsdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=srs_org
      - DOCKER_INFLUXDB_INIT_BUCKET=traffic_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=supersecrettoken123
    restart: unless-stopped

  srs-ui:
    build:
      context: .
      dockerfile: simulator/webapp/Dockerfile.ui
    container_name: srs_ui
    ports:
      - "8080:8080"
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  srs-simulator:
    build:
      context: .
      dockerfile: simulator/Dockerfile.nodo
    container_name: srs_nodes_simulator
    depends_on:
      - mqtt-broker
    restart: unless-stopped

  srs-controller:
    build:
      context: .
      dockerfile: controller/Dockerfile.controller
    container_name: srs_main_controller
    depends_on:
      - influxdb
      - mqtt-broker
    restart: unless-stopped