FROM python:3.10-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apt-get update && \
    apt-get install -y socat && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir mcp fastmcp paho-mqtt influxdb-client
COPY mcp_green_duration.py .
EXPOSE 8001

CMD ["socat", "TCP-LISTEN:8001,fork,reuseaddr", "EXEC:'python -u mcp_green_duration.py'"]