FROM python:3.10-slim
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir fastmcp paho-mqtt influxdb-client

RUN mkdir -p simulator/utility && touch simulator/__init__.py simulator/utility/__init__.py

# Copia il file corretto per il recovery
COPY mcp_servers/recovery/mcp_edge_recovery.py .
COPY simulator/utility/influx_utils.py ./simulator/utility/

EXPOSE 8000

CMD ["python", "-u", "mcp_edge_recovery.py", "--transport", "sse", "--port", "8000"]
