FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY controller/ ./controller/
COPY controller/main_controller.py . 
CMD ["python", "-u", "main_controller.py"]